Issues 25 to 29
CRSU-Apps/MetaBayesDTA pull request #30
Opened 2023-10-23 12:47 UTC by tommorris168

2023-10-24 10:35 UTC, RyanJField approved these changes
This looks good, the release date will need to be changed when pushed to shiny apps. The only suggestion would be host the Cochrane Handbook on GitHub so that it can be updated without pushing a new version of the app. There is the option of making a repo and serving the handbook as a GitHub page so it is accessible from the web.

2023-10-24 10:44 UTC, tommorris168 commented
@RyanJField , do you mean the handbook itself or my instructions?

2023-10-24 10:55 UTC, RyanJField commented
Sorry, your handbook.

2023-10-25 14:15 UTC, RyanJField requested changes

2023-10-25 14:15 UTC, RyanJField commented on README.md
Line 11 should not say beta, perhaps early release.

2023-10-25 18:11 UTC, RyanJField approved these changes
Looks good.

2023-10-26 08:49 UTC, merged